sudo: required
dist: trusty
language: python

python:
  - "2.7"
  - "pypy-5.4.1"

install:
  - pip install -r dev-requirements.txt
  - pip install zschema

script:
  - nosetests ztag
  - ztag -t
  - zschema json ztag/schema.py:ipv4host
  - zschema json ztag/schema.py:website

